### ISSUE TITLE
How to get there

### ISSUE THREAD

**Issue by Driuxdriux** [systemallica/ValenBisi#3]
Hi I'm using your application valembici and it would be great if you added a "How to get there". I personally use it a lot to find places and get to places I haven't been to.
Thanks

**Comment by systemallica** [comment]
Do you mean the ability of adding a marker to the map and getting instructions on how to get there? Like Google Maps?

**Comment by Driuxdriux** [comment]
Exactly

**Comment by systemallica** [comment]
Hi, sorry for getting back to you so late. 

You can tap on a bike station and then on the Google Maps button to open navigation on the Google Maps app. 

As of now I won't develop this feature any further, so I'm closing the issue,
